CREATE TABLE login_token(
	token CHAR(64) NOT NULL PRIMARY KEY,
	userid INTEGER NOT NULL,
	display_name VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastaccessed TIMESTAMP NULL
);

CREATE TABLE oauth_session(
	nonce CHAR(64) NOT NULL PRIMARY KEY,
	status INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	otp VARCHAR(10) NULL,
	token CHAR(64) NULL,
	FOREIGN KEY (token) REFERENCES login_token(token)
);
